%%% Stores the supported keymaps in HydrOS, aswell as the default keymap.
%%% To change the keymap at boot time, simply change the definition of the
%%% DEFAULT_KEYMAP macro.
%%% To add a keymap, add a new list, in the same format as the others, to 
%%% the KEYMAPS macro.

-define(DEFAULT_KEYMAP, "gb").

-record(key, {
	scancode,
	key_characters,
	type
}).

-define(KEYMAPS,[
%       scan                           ctrl          alt    alt    ctrl
%       code      base   shift  ctrl   shift  alt    shift  ctrl   shift
%       ----------------------------------------------------------------
{"gb", [
	#key{scancode = [16#1],  key_characters = [{esc, 27}], type = sys},
	#key{scancode = [16#2],  key_characters = [$1, $!], type = char},
	#key{scancode = [16#3],  key_characters = [$2, $@], type = char},
	#key{scancode = [16#4],  key_characters = [$3, $#], type = char},
	#key{scancode = [16#5],  key_characters = [$4, $$], type = char},
	#key{scancode = [16#6],  key_characters = [$5, $%], type = char},
	#key{scancode = [16#7],  key_characters = [$6, $^], type = char},
	#key{scancode = [16#8],  key_characters = [$7, $&], type = char},
	#key{scancode = [16#9],  key_characters = [$8, $*], type = char},
	#key{scancode = [16#0A], key_characters = [$9, $(], type = char},
	#key{scancode = [16#0B], key_characters = [$0, $)], type = char},
	#key{scancode = [16#0C], key_characters = [$-, $_], type = char},
	#key{scancode = [16#0D], key_characters = [$=, $+], type = char},
	#key{scancode = [16#0E], key_characters = [{bksp, 8}], type = edit},
	#key{scancode = [16#0F], key_characters = [{tab, 9}], type = nav},
	#key{scancode = [16#10], key_characters = [$q, $Q], type = char},
	#key{scancode = [16#11], key_characters = [$w, $W], type = char},
	#key{scancode = [16#12], key_characters = [$e, $E], type = char},
	#key{scancode = [16#13], key_characters = [$r, $R], type = char},
	#key{scancode = [16#14], key_characters = [$t, $T], type = char},
	#key{scancode = [16#15], key_characters = [$y, $Y], type = char},
	#key{scancode = [16#16], key_characters = [$u, $U], type = char},
	#key{scancode = [16#17], key_characters = [$i, $I], type = char},
	#key{scancode = [16#18], key_characters = [$o, $O], type = char},
	#key{scancode = [16#19], key_characters = [$p, $P], type = char},
	#key{scancode = [16#1A], key_characters = [$[, ${], type = char},
	#key{scancode = [16#1B], key_characters = [$], $}], type = char},
	#key{scancode = [16#1C], key_characters = [{enter, 13}], type = edit},
	#key{scancode = [16#1D], key_characters = [ctrl], type = mod},
	#key{scancode = [16#1E], key_characters = [$a, $A], type = char},
	#key{scancode = [16#1F], key_characters = [$s, $S], type = char},
	#key{scancode = [16#20], key_characters = [$d, $D], type = char},
	#key{scancode = [16#21], key_characters = [$f, $F], type = char},
	#key{scancode = [16#22], key_characters = [$g, $G], type = char},
	#key{scancode = [16#23], key_characters = [$h, $H], type = char},
	#key{scancode = [16#24], key_characters = [$j, $J], type = char},
	#key{scancode = [16#25], key_characters = [$k, $K], type = char},
	#key{scancode = [16#26], key_characters = [$l, $L], type = char},
	#key{scancode = [16#27], key_characters = [$;, $:], type = char},
	#key{scancode = [16#28], key_characters = [$', $"], type = char},
	#key{scancode = [16#29], key_characters = [$`, $~], type = char},
	#key{scancode = [16#2A], key_characters = [shift], type = mod},
	#key{scancode = [16#2B], key_characters = [$\\, $|], type = char},
	#key{scancode = [16#2C], key_characters = [$z, $Z], type = char},
	#key{scancode = [16#2D], key_characters = [$x, $X], type = char},
	#key{scancode = [16#2E], key_characters = [$c, $C], type = char},
	#key{scancode = [16#2F], key_characters = [$v, $V], type = char},
	#key{scancode = [16#30], key_characters = [$b, $B], type = char},
	#key{scancode = [16#31], key_characters = [$n, $N], type = char},
	#key{scancode = [16#32], key_characters = [$m, $M], type = char},
	#key{scancode = [16#33], key_characters = [$,, $<], type = char},
	#key{scancode = [16#34], key_characters = [$., $>], type = char},
	#key{scancode = [16#35], key_characters = [$/, $?], type = char},
	% rshift = shift
	#key{scancode = [16#36], key_characters = [shift], type = mod},
	#key{scancode = [16#37], key_characters = [prtsc], type = sys},
	#key{scancode = [16#38], key_characters = [alt], type = mod},
	#key{scancode = [16#39], key_characters = [$ ], type = char},
	#key{scancode = [16#3A], key_characters = [caps_lock], type = lock},
	#key{scancode = [16#3B], key_characters = [f1], type = func},
	#key{scancode = [16#3C], key_characters = [f2], type = func},
	#key{scancode = [16#3D], key_characters = [f3], type = func},
	#key{scancode = [16#3E], key_characters = [f4], type = func},
	#key{scancode = [16#3F], key_characters = [f5], type = func},
	#key{scancode = [16#40], key_characters = [f6], type = func},
	#key{scancode = [16#41], key_characters = [f7], type = func},
	#key{scancode = [16#42], key_characters = [f8], type = func},
	#key{scancode = [16#43], key_characters = [f9], type = func},
	#key{scancode = [16#44], key_characters = [f10], type = func},
	#key{scancode = [16#45], key_characters = [numl], type = lock},
	#key{scancode = [16#46], key_characters = [scrl], type = lock},
	#key{scancode = [16#47], key_characters = [home], type = numpad},
	#key{scancode = [16#48], key_characters = [up], type = nav},
	#key{scancode = [16#49], key_characters = [pgup], type = nav},
	#key{scancode = [16#4A], key_characters = [$-], type = char},
	#key{scancode = [16#4B], key_characters = [left], type = nav},
	#key{scancode = [16#4C], key_characters = [center], type = numpad},
	#key{scancode = [16#4D], key_characters = [right], type = nav},
	#key{scancode = [16#4E], key_characters = [$+], type = char},
	#key{scancode = [16#4F], key_characters = ['end'], type = nav},
	#key{scancode = [16#50], key_characters = [down], type = nav},
	#key{scancode = [16#51], key_characters = [pgdn], type = nav},
	#key{scancode = [16#52], key_characters = [ins], type = edit},
	#key{scancode = [16#53], key_characters = [del], type = edit},
	#key{scancode = [16#57], key_characters = [f11], type = func},
	#key{scancode = [16#58], key_characters = [f12], type = func},
	#key{scancode = [16#E0, 16#35], key_characters = [$/], type = char},
	#key{scancode = [16#E0, 16#1C], key_characters = [{enter, 13}], type = edit},
	#key{scancode = [16#E0, 16#52], key_characters = [ins], type = edit},
	#key{scancode = [16#E0, 16#53], key_characters = [del], type = edit},
	#key{scancode = [16#E0, 16#47], key_characters = [home], type = nav},
	#key{scancode = [16#E0, 16#4F], key_characters = ['end'], type = nav},
	#key{scancode = [16#E0, 16#49], key_characters = [pgup], type = nav},
	#key{scancode = [16#E0, 16#51], key_characters = [pgdn], type = nav},
	#key{scancode = [16#E0, 16#4B], key_characters = [left], type = nav},
	#key{scancode = [16#E0, 16#4D], key_characters = [right], type = nav},
	#key{scancode = [16#E0, 16#48], key_characters = [up], type = nav},
	#key{scancode = [16#E0, 16#50], key_characters = [down], type = nav},
	% ralt = alt
	#key{scancode = [16#E0, 16#38], key_characters = [alt], type = mod}, 
	% rctrl = ctrl
	#key{scancode = [16#E0, 16#1D], key_characters = [ctrl], type = mod}] 
},
%% The swedish key map uses a different layout, due to the number of characters
%% required in the key_char field. Both layouts are acceptable.
{"se", [
	{key, [002],   [$1,    $!,    nop,   nop,   nop,   nop,   nop,   nop], char},
	{key, [003],   [$2,    $",    0,     0,     $@,    $@,    $@,    0  ], char},
	{key, [004],   [$3,    $#,    nop,   nop,   16#a3, nop,   nop,   nop], char},
	{key, [005],   [$4,    16#a4, nop,   nop,   $$,    nop,   nop,   nop], char},
	{key, [006],   [$5,    $%,    nop,   nop,   nop,   nop,   nop,   nop], char},
	{key, [007],   [$6,    $&,    nop,   nop,   nop,   nop,   nop,   nop], char},
	{key, [008],   [$7,    $/,    nop,   nop,   ${,    nop,   nop,   nop], char},
	{key, [009],   [$8,    $(,    nop,   nop,   $[,    nop,   nop,   nop], char},
	{key, [010],   [$9,    $),    nop,   nop,   $],    nop,   gs,    nop], char},
	{key, [011],   [$0,    $=,    nop,   nop,   $},    nop,   nop,   nop], char},
	{key, [012],   [$+,    $?,    nop,   nop,   $\\,   nop,   fs,    nop], char},
	{key, [013],   [16#80, $`,    nop,   nop,   nop,   nop,   nop,   nop], char},
	{key, [016],   [$q,    $Q,    17,    17,    $q,    $Q,    17,    17 ], char},
	{key, [017],   [$w,    $W,    23,    23,    $w,    $W,    23,    23 ], char},
	{key, [018],   [$e,    $E,    5,     5,     $€,    $E,    5,     5  ], char},
	{key, [019],   [$r,    $R,    18,    18,    $r,    $R,    18,    18 ], char},
	{key, [020],   [$t,    $T,    20,    20,    $t,    $T,    20,    20 ], char},
	{key, [021],   [$y,    $Y,    25,    25,    $y,    $Y,    25,    25 ], char},
	{key, [022],   [$u,    $U,    21,    21,    $u,    $U,    21,    21 ], char},
	{key, [023],   [$i,    $I,    9,     9,     $i,    $I,    9,     9  ], char},
	{key, [024],   [$o,    $O,    15,    15,    $o,    $O,    15,    15 ], char},
	{key, [025],   [$p,    $P,    16,    16,    $p,    $P,    16,    16 ], char},
	{key, [026],   [16#e5, 16#c5, nop,   nop,   $},    $],    nop,   nop], char},
	{key, [027],   [16#a8, $^,    nop,   nop,   $~,    nop,   nop,   nop], char},
	{key, [030],   [$a,    $A,    1,     1,     $a,    $A,    1,     1  ], char},
	{key, [031],   [$s,    $S,    19,    19,    $s,    $S,    19,    19 ], char},
	{key, [032],   [$d,    $D,    4,     4,     $d,    $D,    4,     4  ], char},
	{key, [033],   [$f,    $F,    46,    46,    $f,    $F,    46,    46 ], char},
	{key, [034],   [$g,    $G,    7,     7,     $g,    $G,    7,     7  ], char},
	{key, [035],   [$h,    $H,    8,     8,     $h,    $H,    8,     8  ], char},
	{key, [036],   [$j,    $J,    10,    10,    $j,    $J,    10,    10 ], char},
	{key, [037],   [$k,    $K,    11,    11,    $k,    $K,    11,    11 ], char},
	{key, [038],   [$l,    $L,    12,    12,    $l,    $L,    12,    12 ], char},
	{key, [039],   [16#f6, 16#d6, nop,   nop,   $|,    $\\,   nop,   nop], char},
	{key, [040],   [16#e4, 16#c4, nop,   nop,   ${,    $[,    nop,   nop], char},
	{key, [041],   [16#a7, 16#bd, nop,   nop,   nop,   $|,    nop,   nop], char},
	{key, [043],   [$',    $*,    nop,   nop,   nop,   nop,   nop,   nop], char},
	{key, [044],   [$z,    $Z,    26,    26,    $z,    $Z,    26,    26 ], char},
	{key, [045],   [$x,    $X,    24,    24,    $x,    $X,    24,    24 ], char},
	{key, [046],   [$c,    $C,    3,     3,     $c,    $C,    3,     3  ], char},
	{key, [047],   [$v,    $V,    22,    22,    $v,    $V,    22,    22 ], char},
	{key, [048],   [$b,    $B,    2,     2,     $b,    $B,    2,     2  ], char},
	{key, [049],   [$n,    $N,    14,    14,    $n,    $N,    14,    14 ], char},
	{key, [050],   [$m,    $M,    13,    13,    $m,    $M,    13,    13 ], char},
	{key, [051],   [$,,    $;,    nop,   nop,   nop,   $<,    nop,   nop], char},
	{key, [052],   [$.,    $:,    nop,   nop,   nop,   $>,    nop,   nop], char},
	{key, [053],   [$-,    $_,    31,    nop,   $/,    $?,    nop,   nop], char},
	{key, [086],   [$<,    $>,    nop,   nop,   $|,    nop,   nop,   nop], char},
	{key, [16#E0, 16#38],   [ctrl,alt], mod}]  % ralt = alt-gr
}
]).
